version: "3.8"
services:
  # MongoDB Service
  mongo:
    image: mongo:6.0.12
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - mongoConf:/data/configdb
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitMQData:/var/lib/rabbitmq/
      - rabbitMQLogs:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${MESSAGE_BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${MESSAGE_BROKER_PASSWORD}

  order-management-ui:
    restart: always
    build:
      context: ./order-management-ui
      dockerfile: Dockerfile
      args:
        - VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN=${VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN}
    ports:
      - "80:80" # Map port 3000 of the container to port 80 on the host

  kitchen-service:
    restart: always
    build:
      context: ./kitchen-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 of the container to port 8080 on the host
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - MESSAGE_BROKER_USER=${MESSAGE_BROKER_USER}
      - MESSAGE_BROKER_PASSWORD=${MESSAGE_BROKER_PASSWORD}
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_PORT=${MESSAGE_BROKER_PORT}
      - INGREDIENTS_CHECK_QUEUE=${INGREDIENTS_CHECK_QUEUE}
    command: npm run start
    depends_on:
      - mongo
      - rabbitmq

  warehouse-service:
    restart: always
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Map port 8080 of the container to port 8081 on the host
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - MESSAGE_BROKER_USER=${MESSAGE_BROKER_USER}
      - MESSAGE_BROKER_PASSWORD=${MESSAGE_BROKER_PASSWORD}
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_PORT=${MESSAGE_BROKER_PORT}
      - INGREDIENTS_CHECK_QUEUE=${INGREDIENTS_CHECK_QUEUE}
    command: npm run start
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo:
  mongoConf:
  rabbitMQData:
  rabbitMQLogs:
