const { MODE, VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN } = import.meta.env;

export const KITCHEN_PORT_SERVICE = 8080;
export const WAREHOUSE_PORT_SERVICE = 8081;
export const KITCHEN_API_PATH_SUFFIX = "api/v1/kitchen";
export const WAREHOUSE_API_PATH_SUFFIX = "api/v1/warehouse";

export const KITCHEN_SERVICE_DOMAIN =
  MODE === "production"
    ? `http://${VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN}`
    : `http://${VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN}:${KITCHEN_PORT_SERVICE}`;

export const WAREHOUSE_SERVICE_DOMAIN =
  MODE === "production"
    ? `http://${VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN}`
    : `http://${VITE_RESTAURANT_ORDER_SYSTEM_DOMAIN}:${WAREHOUSE_PORT_SERVICE}`

